### ISSUE TITLE
Google Assistant App Actions support 

### ISSUE THREAD

**Issue by machinehead** [NePheus/capacitor-android-shortcuts#10]
If my understanding of the documentation is correct, this plugin might be a great place to implement support for Google Assistant's App Actions as dynamic shortcuts ( https://developer.android.com/guide/app-actions/get-started ). I wasn't able to find support for that elsewhere in Capacitor's ecosystem.

This is something I could attempt adding myself. Please advise on whether such a contribution would be welcome here.

**Comment by NePheus** [comment]
I never used App Actions, so I dont know how it works under the hood. But if you think the combination of App Actions and Dynamic Shortcut make sense and there are some interfaces between, you could just create a PR with an idea how to integrate it in a useful way.

If we decide in the end that it would be more useful to create an new plugin, I would also be ok when you copy all needed code from this plugin to make it work.

**Comment by machinehead** [comment]
Thank you! 

I'm very new to Android development - if I do take a look into this, it'll be my first project with Android ever.
I'll keep thinking about this and will create a PR if/when I get to this.
