### ISSUE TITLE
Capacitor v4 support

### ISSUE THREAD

**Issue by NLueg** [NePheus/capacitor-android-shortcuts#5]
Capacitor v4 has been released and it would be great for this plugin to support v4.
The required change is actually quite small. An example migration can be found here: https://github.com/capacitor-community/http/pull/275/files

If you have no time to do so I will create a PR for it. But currently I don't have any time either.

**Comment by NePheus** [comment]
https://github.com/NePheus/capacitor-android-shortcuts/pull/6

**Comment by NLueg** [comment]
Oh wow, that was fast 😄 Thank you @NePheus!
