### ISSUE TITLE
Feature: Ability to update dynamic shortcuts

### ISSUE THREAD

**Issue by piotr-cz** [NePheus/capacitor-android-shortcuts#7]
At this moment after dynamic shortcuts have been added, there is no possibility to manage them (update/ remove).

Suggestion:
Adding `AndroidShortcuts.setDynamic` method which would call [ShortcutManagerCompat::setDynamicShortcuts](https://developer.android.com/reference/androidx/core/content/pm/ShortcutManagerCompat#setDynamicShortcuts(android.content.Context,java.util.List%3Candroidx.core.content.pm.ShortcutInfoCompat%3E))

Rererence: Android for Developers > [Manage Shortcuts](https://developer.android.com/develop/ui/views/launch/shortcuts/managing-shortcuts)

**Comment by piotr-cz** [comment]
Update: it seems that it's already being used by `AndroidShortcuts.addDynamic`

https://github.com/NePheus/capacitor-android-shortcuts/blob/72183df8b85903d357419f572608119ba651cd0d/android/src/main/java/nepheus/capacitor/androidshortcuts/AndroidShortcuts.java#L70

but it was not obvious from the documentation

**Comment by piotr-cz** [comment]
After that you may re-add proxy method addDynamic and mark is as deprecated to prevent breaking change

**Comment by NePheus** [comment]
Do you know a good way to implement such proxy methods? As there is no JS code between when I call the method, and the native code is called directly, I could just add the old and new methods in the definitions.ts and also in the java file, and there I could redirect the old methods to the new one. Inside the definitions.ts I could mark them as deprecated in the comment.

**Comment by NePheus** [comment]
I just released 5.0.2.

**Comment by piotr-cz** [comment]
Thanks!
One more thing: I'd mark methods as deprecated in the docs, or even remove them: https://github.com/NePheus/capacitor-android-shortcuts/commit/88b1faab920c51d01a81b210a3e85d15b06bb7e0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R182-R215

**Comment by NePheus** [comment]
Didnt realize that. Its cazsed by the automatic docs generation. Maybe I will also add a "deprecated" there to the description.

**Comment by NePheus** [comment]
Tried `@ignore` iniside the definitions.ts but its still showing in the readme.md. Then I read somewhere that this is not going to work. I just updated the description of both methods now.
