### ISSUE TITLE
Capacitor v5 support

### ISSUE THREAD

**Issue by piotr-cz** [NePheus/capacitor-android-shortcuts#9]
Capacitor v5 have been [released recently](https://ionic.io/blog/announcing-capacitor-5).

**Comment by NePheus** [comment]
Yes, this plugin is already migrated to it with v5.0.4.

**Comment by piotr-cz** [comment]
`@capacitor/core` is set as a dependency at ^4.0.0:

https://github.com/NePheus/capacitor-android-shortcuts/blob/c6a6bd2f82fe1d513ea8e6e7a06870ce8f904169/package.json#L45

**Comment by NePheus** [comment]
Thanks. I published a fix with 5.0.5.
